import my_exceptions

print("hello world")
